<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>me.justeli.countrybanners</groupId>
        <artifactId>CountryBanners</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>countrybanners-combined</artifactId>

    <properties>
        <plugin.name>${project.name}</plugin.name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>me.justeli.countrybanners</groupId>
            <artifactId>countrybanners-core</artifactId>
            <version>${revision}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.justeli.countrybanners.paper</groupId>
            <artifactId>countrybanners-paper</artifactId>
            <version>${revision}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.justeli.countrybanners.spigot</groupId>
            <artifactId>countrybanners-spigot</artifactId>
            <version>${revision}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
